<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <RootNamespace>funscrew</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="libs\**" />
    <EmbeddedResource Remove="libs\**" />
    <None Remove="libs\**" />
  </ItemGroup>


  <ItemGroup>
    <PackageReference Include="CommandLineParser" Version="2.9.1" />
    <PackageReference Include="drewCo.Tools" Version="1.5.0" />
  </ItemGroup>


  <!--Conditional Compilation Symbols-->
  <PropertyGroup Condition="$([MSBuild]::IsOSPlatform('Windows'))">
    <DefineConstants>OS_WINDOWS</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="$([MSBuild]::IsOSPlatform('Linux'))">
    <DefineConstants>OS_LINUX</DefineConstants>
  </PropertyGroup>


  <Target Name="CopyLibs" AfterTargets="Build">
    <!--Example of conditional includes....-->
    <!--<ItemGroup Condition="'$(OS)' == 'Windows_NT'">
      <NativeFiles Include="NativeLibs/win-x64/**/*.*" />
    </ItemGroup>

    <ItemGroup Condition="'$(OS)' != 'Windows_NT'">
      <NativeFiles Include="NativeLibs/linux-x64/**/*.*" />
    </ItemGroup>-->

    <ItemGroup>
      <ExtraFiles Include="../libs/$(Configuration)/*.*" />
    </ItemGroup>

    <Copy SourceFiles="@(ExtraFiles)" DestinationFiles="@(ExtraFiles->'$(OutputPath)%(Filename)%(Extension)')" SkipUnchangedFiles="true" />
  </Target>

</Project>
