# These are all commands that were converted from the project "ReplayAppliance"

# @ALIAS session-request
[SessionRequestOptions]

# Host address to make the request on.
Host = "localhost"

#(TCP) Port to listen on for session start requests.
Port = 5000

# Request timeout in milliseconds
Timeout = 5000

MaxPlayerCount = 2
TotalInputSize = 10
GameName = "sfiii3nr1"
GameVersion = "0.5a"
PlayerNames = "Echoman, Screwie"


# @ALIAS replay-appliance
[ReplayApplianceOptions]

# (TCP) Port to listen on for session start requests.
# @ALIAS --service-port
ServicePort = 5000

# (UDP) Port where replay data will be sent.
# @ALIAS --replay-port
ReplayPort = 7002

# If set, leaves a test session with ID 12345 always running.  Don't do this in production tho!
# @ALIAS --use-test-session
UseTestSession = false

ReplayDataDir = "replay-data"


# @ALIAS input-echo
[InputEchoOptions]
# The name of the game that we are playing.
# @ALIAS --game-name
# @REQUIRED
GameName = ""

# The player number: 1, 2, etc.
# @ALIAS --player
# @REQUIRED
PlayerNumber = -1

# Name of the player
# @ALIAS --name
# @REQUIRED
PlayerName = ""

# Comma delimited list of all <host>:<port>-<playerNumber> of the remote players that we expect to connect to.  NOTE: Currently only one remote player is supported!
# @ALIAS --remote
# @REQUIRED
RemotePlayers = "127.0.0.1:7001-2"

# If set, the left/right controls will be inverted when echoing the input.
# @ALIAS --invert-controls
InvertLeftRightControls = true

# How many frames should the echo be delayed?
# @ALIAS --delay-frames
DelayFrameCount = 30


LocalPort = 7000

# Address of the replay applicance in the form of: <host>:<port>
# @ALIAS --replay-options
# @REQUIRED
ReplayAddress = ""

# Time in ms. that attempts to sync will time out.  Gameplay will continue as normal, but no replay data will be sent.
# @ALIAS --replay-timeout
ReplayTimeout = 5000

# Session ID.  This should match between clients and should be unique.
# @ALIAS --session-id
SessionId = 12345

ProtocolVersion = 4

